require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe VotablesController do

  def mock_votable(stubs={})
    @mock_votable ||= mock_model(Votable, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all votables as @votables" do
      Votable.stub(:all) { [mock_votable] }
      get :index
      assigns(:votables).should eq([mock_votable])
    end
  end

  describe "GET show" do
    it "assigns the requested votable as @votable" do
      Votable.stub(:find).with("37") { mock_votable }
      get :show, :id => "37"
      assigns(:votable).should be(mock_votable)
    end
  end

  describe "GET new" do
    it "assigns a new votable as @votable" do
      Votable.stub(:new) { mock_votable }
      get :new
      assigns(:votable).should be(mock_votable)
    end
  end

  describe "GET edit" do
    it "assigns the requested votable as @votable" do
      Votable.stub(:find).with("37") { mock_votable }
      get :edit, :id => "37"
      assigns(:votable).should be(mock_votable)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created votable as @votable" do
        Votable.stub(:new).with({'these' => 'params'}) { mock_votable(:save => true) }
        post :create, :votable => {'these' => 'params'}
        assigns(:votable).should be(mock_votable)
      end

      it "redirects to the created votable" do
        Votable.stub(:new) { mock_votable(:save => true) }
        post :create, :votable => {}
        response.should redirect_to(votable_url(mock_votable))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved votable as @votable" do
        Votable.stub(:new).with({'these' => 'params'}) { mock_votable(:save => false) }
        post :create, :votable => {'these' => 'params'}
        assigns(:votable).should be(mock_votable)
      end

      it "re-renders the 'new' template" do
        Votable.stub(:new) { mock_votable(:save => false) }
        post :create, :votable => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested votable" do
        Votable.stub(:find).with("37") { mock_votable }
        mock_votable.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :votable => {'these' => 'params'}
      end

      it "assigns the requested votable as @votable" do
        Votable.stub(:find) { mock_votable(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:votable).should be(mock_votable)
      end

      it "redirects to the votable" do
        Votable.stub(:find) { mock_votable(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(votable_url(mock_votable))
      end
    end

    describe "with invalid params" do
      it "assigns the votable as @votable" do
        Votable.stub(:find) { mock_votable(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:votable).should be(mock_votable)
      end

      it "re-renders the 'edit' template" do
        Votable.stub(:find) { mock_votable(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested votable" do
      Votable.stub(:find).with("37") { mock_votable }
      mock_votable.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the votables list" do
      Votable.stub(:find) { mock_votable }
      delete :destroy, :id => "1"
      response.should redirect_to(votables_url)
    end
  end

end
